# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88d28a27c7eeaddb7c614092f3a2246120a0fb377545ea4886f64e42f246f5748fff1af2ea9284efdff50dfcc291b36d83090f236335b2d518032d60cb06ad4b

test:
  secret_key_base: e98088c30490ec6c9a73624e769d76d8a6f494a28ab5a97f759ed01a43086f846afd104b048b7620eebd608ade85864c64cf9addf10cfd16eed1eb88755f5c3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
